Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/MethodCallWithoutArgsParentheses:
   Enabled: false 

Style/MultilineBlockChain:
  Enabled: false  
  
Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/theatre_spec.rb'
    - 'spec/netflix_spec.rb'
    - 'spec/new_movie_spec.rb'
    - 'spec/modern_movie_spec.rb'
    - 'spec/classic_movie_spec.rb'
    - 'spec/ancient_movie_spec.rb'
    - 'spec/movie_collection_spec.rb'
    - 'spec/movie_spec.rb'
    - 'cinematheque.gemspec'
    - 'Gemfile'
    - 'Gemfile.lock'


