Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

AllCops:
  Exclude:
    - 'spec/movie_collection_spec.rb'
    - 'spec/movie_spec.rb'
    - 'cinematheque.gemspec'
    - 'Gemfile'
    - 'Gemfile.lock'


